import { ThemeTypes } from './enums';
import { KeyCombo, Theme } from './models';

export const KEY_COMBOS: Record<string, KeyCombo> = {
    keya: {
        key: 65,
        en: 'a',
        plain: 'ཏ',
        shift: 'ྟ',
        alt: 'ཊ',
        shiftAlt: 'ྚ',
    },
    keyb: {
        key: 66,
        en: 'b',
        plain: 'ར',
        shift: 'ྲ',
        alt: '',
        shiftAlt: 'ྼ',
    },
    keyc: {
        key: 67,
        en: 'c',
        plain: 'འ',
        shift: 'ཱ',
        alt: '',
        shiftAlt: 'ྰ',
    },
    keyd: {
        key: 68,
        en: 'd',
        plain: 'ད',
        shift: 'ྡ',
        alt: 'ཌ',
        shiftAlt: 'ྜ',
    },
    keye: {
        key: 69,
        en: 'e',
        plain: 'ག',
        shift: 'ྒ',
        alt: '',
        shiftAlt: '',
    },
    keyf: {
        key: 70,
        en: 'f',
        plain: 'ན',
        shift: 'ྣ',
        alt: 'ཎ',
        shiftAlt: 'ྞ',
    },
    keyg: {
        key: 71,
        en: 'g',
        plain: 'པ',
        shift: 'ྤ',
        alt: '',
        shiftAlt: '',
    },
    keyh: {
        key: 72,
        en: 'h',
        plain: 'ཕ',
        shift: 'ྥ',
        alt: '',
        shiftAlt: '',
    },
    keyi: {
        key: 73,
        en: 'i',
        plain: 'ོ',
        shift: 'ཽ',
        alt: '',
        shiftAlt: '',
    },
    keyj: {
        key: 74,
        en: 'j',
        plain: 'བ',
        shift: 'ྦ',
        alt: '',
        shiftAlt: '',
    },
    keyk: {
        key: 75,
        en: 'k',
        plain: 'མ',
        shift: 'ྨ',
        alt: '',
        shiftAlt: '',
    },
    keyl: {
        key: 76,
        en: 'l',
        plain: 'ཙ',
        shift: 'ྩ',
        alt: '',
        shiftAlt: '',
    },
    keym: {
        key: 77,
        en: 'm',
        plain: 'ཤ',
        shift: 'ྴ',
        alt: '',
        shiftAlt: '',
    },
    keyn: {
        key: 78,
        en: 'n',
        plain: 'ལ',
        shift: 'ླ',
        alt: '',
        shiftAlt: '',
    },
    keyo: {
        key: 79,
        en: 'o',
        plain: 'ཅ',
        shift: 'ྕ',
        alt: '',
        shiftAlt: '',
    },
    keyp: {
        key: 80,
        en: 'p',
        plain: 'ཆ',
        shift: 'ྖ',
        alt: '',
        shiftAlt: '',
    },
    keyq: {
        key: 81,
        en: 'q',
        plain: 'ཀ',
        shift: 'ྐ',
        alt: '',
        shiftAlt: '',
    },
    keyr: {
        key: 82,
        en: 'r',
        plain: 'ང',
        shift: 'ྔ',
        alt: 'ྃ',
        shiftAlt: '',
    },
    keys: {
        key: 83,
        en: 's',
        plain: 'ཐ',
        shift: 'ྠ',
        alt: 'ཋ',
        shiftAlt: 'ྛ',
    },
    keyt: {
        key: 84,
        en: 't',
        plain: 'ི',
        shift: 'ྀ',
        alt: '',
        shiftAlt: '',
    },
    keyu: {
        key: 85,
        en: 'u',
        plain: 'ེ',
        shift: 'ཻ',
        alt: '',
        shiftAlt: '',
    },
    keyv: {
        key: 86,
        en: 'v',
        plain: 'ཡ',
        shift: 'ྱ',
        alt: '',
        shiftAlt: 'ྻ',
    },
    keyw: {
        key: 87,
        en: 'w',
        plain: 'ཁ',
        shift: 'ྑ',
        alt: '',
        shiftAlt: '',
    },
    keyx: {
        key: 88,
        en: 'x',
        plain: 'ཟ',
        shift: 'ྯ',
        alt: '',
        shiftAlt: '',
    },
    keyy: {
        key: 89,
        en: 'y',
        plain: 'ུ',
        shift: '྄',
        alt: '',
        shiftAlt: '',
    },
    keyz: {
        key: 90,
        en: 'z',
        plain: 'ཞ',
        shift: 'ྮ',
        alt: '',
        shiftAlt: '',
    },
    digit0: {
        key: 48,
        en: '0',
        plain: '༠',
        shift: '༽',
        alt: '',
        shiftAlt: '',
    },
    digit1: {
        key: 49,
        en: '1',
        plain: '༡',
        shift: '༄',
        alt: '',
        shiftAlt: '',
    },
    digit2: {
        key: 50,
        en: '2',
        plain: '༢',
        shift: '༅',
        alt: '',
        shiftAlt: '',
    },
    digit3: {
        key: 51,
        en: '3',
        plain: '༣',
        shift: '༆',
        alt: '',
        shiftAlt: '',
    },
    digit4: {
        key: 52,
        en: '4',
        plain: '༤',
        shift: 'Nu.',
        alt: '',
        shiftAlt: '',
    },
    digit5: {
        key: 53,
        en: '5',
        plain: '༥',
        shift: '༎',
        alt: '',
        shiftAlt: '',
    },
    digit6: {
        key: 54,
        en: '6',
        plain: '༦',
        shift: '༈',
        alt: '',
        shiftAlt: '',
    },
    digit7: {
        key: 55,
        en: '7',
        plain: '༧',
        shift: '༸',
        alt: '',
        shiftAlt: '',
    },
    digit8: {
        key: 56,
        en: '8',
        plain: '༨',
        shift: '༴',
        alt: '',
        shiftAlt: '',
    },
    digit9: {
        key: 57,
        en: '9',
        plain: '༩',
        shift: '༼',
        alt: '',
        shiftAlt: '',
    },
    semicolon: {
        key: 186,
        en: ';',
        plain: 'ཚ',
        shift: 'ྪ',
        alt: '',
        shiftAlt: '',
    },
    equal: {
        key: 187,
        en: '=',
        plain: '།',
        shift: '༑',
        alt: '',
        shiftAlt: '',
    },
    comma: {
        key: 188,
        en: ',',
        plain: 'ས',
        shift: 'ྶ',
        alt: '',
        shiftAlt: '',
    },
    minus: {
        key: 189,
        en: '-',
        plain: '༔',
        shift: 'ཿ',
        alt: '',
        shiftAlt: '',
    },
    period: {
        key: 190,
        en: '.',
        plain: 'ཧ',
        shift: 'ྷ',
        alt: '',
        shiftAlt: '',
    },
    slash: {
        key: 191,
        en: '/',
        plain: 'ཨ',
        shift: 'ྸ',
        alt: '',
        shiftAlt: '\u003F',
    },
    backquote: {
        key: 192,
        en: '`',
        plain: '༉',
        shift: '༊',
        alt: '࿑',
        shiftAlt: '࿐',
    },
    bracketleft: {
        key: 219,
        en: '[',
        plain: 'ཇ',
        shift: 'ྗ',
        alt: '\u0028',
        shiftAlt: '',
    },
    backslash: {
        key: 220,
        en: '\\',
        plain: 'ཝ',
        shift: 'ྭ',
        alt: '',
        shiftAlt: 'ྺ',
    },
    bracketright: {
        key: 221,
        en: ']',
        plain: 'ཉ',
        shift: 'ྙ',
        alt: '\u0029',
        shiftAlt: '',
    },
    quote: {
        key: 222,
        en: "'",
        plain: 'ཛ',
        shift: 'ྫ',
        alt: '',
        shiftAlt: '',
    },
    space: {
        key: 32,
        en: '',
        plain: '་',
        shift: '\u0020',
        alt: '༌',
        shiftAlt: '',
    },
};

export const NUMBERS_EN_TO_DZO: Record<number, string> = {
    0: '༠',
    1: '༡',
    2: '༢',
    3: '༣',
    4: '༤',
    5: '༥',
    6: '༦',
    7: '༧',
    8: '༨',
    9: '༩',
};

export const NUMBERS_DZO_TO_EN: Record<string, string> = {
    '༠': '0',
    '༡': '1',
    '༢': '2',
    '༣': '3',
    '༤': '4',
    '༥': '5',
    '༦': '6',
    '༧': '7',
    '༨': '8',
    '༩': '9',
};

// symbols with same height are grouped so that gradient combination can be applied later
// the names for these groups are based on symbol position 
// appropriate group names should be applied in a later commit if applicable

export const WORD_GROUPS: Record<string, string[]> = {
    mainSymbolsLong: ['ཉ', 'ཧ', 'ཞ', 'ད', 'ག', 'ན', 'ཤ', 'ཀ'],
    mainSymbolsShort: ['ཏ', 'ཛ', 'ཝ', 'ཇ', 'ཨ', 'ས', 'ཚ', 'ཟ', 'ཁ', 'ཡ', 'ར', 'འ', 'པ', 'ཕ', 'བ', 'མ', 'ཙ', 'ལ', 'ཅ', 'ཆ', 'ང', 'ཐ'],
    subscripts1: ['ྫ', 'ྙ', 'ྗ', 'ྸ', 'ྷ', 'ྶ', 'ྪ', 'ྮ', 'ྯ', 'ྑ', 'ྟ', 'ྡ', 'ྒ', 'ྣ', 'ྤ', 'ྥ', 'ྦ', 'ྨ', 'ྩ', 'ྴ', 'ྕ', 'ྖ', 'ྐ', 'ྔ', 'ྠ'],
    subscripts2: ['ྭ'],
    subscripts3: ['ྱ'],
    subscripts4: ['ྲ'],
    subscripts5: ['ུ'],
    subscripts6: ['ཱ'],
    subscripts7: ['ླ'],
    superscripts1: ['ི', 'ེ', 'ོ'],
    superscripts2: ['ལ', 'ས'],
    superscripts3: ['ར']
}


export const SPECIAL_KEY_IDS: string[] = ['shiftleft', 'shiftright', 'altright', 'altleft', 'capslock', 'controlleft', 'controlleft'];


export const GAME_MODE_SETTINGS: Record<string, {
  totalTime: string,
  wordAddTime: number,
  wordRemoveTime?: number
}> = {
    easy: {
        totalTime: '༣་༠༠',
        wordAddTime: 500,
    },
    falling_words: {
        totalTime: '༥་༠༠',
        wordAddTime: 3000
    },
};

export const GAME_MODES: string[] = ['easy', 'falling_words'];

export const THEME: Record<ThemeTypes, Theme> = {
    light: {
        colors: {
            highlight: '#d3e0ea',
            text: '#1687a7'
        }
    }
}

export const AVERAGE_SCORE = 35;